set destinationDir=.\Assets\Plugins\
set csharpDir=..\..\..\csharp\win64\
set nativeDir=..\..\..\win64\vc14.1\bin\

xcopy "%csharpDir%CadExA3DSNet.dll"    "%destinationDir%" /y
xcopy "%csharpDir%CadExACISNet.dll"    "%destinationDir%" /y
xcopy "%csharpDir%CadExAdvGeomNet.dll" "%destinationDir%" /y
xcopy "%csharpDir%CadExBRepNet.dll"    "%destinationDir%" /y
xcopy "%csharpDir%CadExCATNet.dll"     "%destinationDir%" /y
xcopy "%csharpDir%CadExColladaNet.dll" "%destinationDir%" /y
xcopy "%csharpDir%CadExCoreNet.dll"    "%destinationDir%" /y
xcopy "%csharpDir%CadExCreoNet.dll"    "%destinationDir%" /y
xcopy "%csharpDir%CadExDS3DXMLNet.dll" "%destinationDir%" /y
xcopy "%csharpDir%CadExDWGNet.dll"     "%destinationDir%" /y
xcopy "%csharpDir%CadExDXFNet.dll"     "%destinationDir%" /y
xcopy "%csharpDir%CadExFBXNet.dll"     "%destinationDir%" /y
xcopy "%csharpDir%CadExGLTFNet.dll"    "%destinationDir%" /y
xcopy "%csharpDir%CadExIFCNet.dll"     "%destinationDir%" /y
xcopy "%csharpDir%CadExIGESNet.dll"    "%destinationDir%" /y
xcopy "%csharpDir%CadExINVNet.dll"     "%destinationDir%" /y
xcopy "%csharpDir%CadExJTNet.dll"      "%destinationDir%" /y
xcopy "%csharpDir%CadExMeshNet.dll"    "%destinationDir%" /y
xcopy "%csharpDir%CadExNXNet.dll"      "%destinationDir%" /y
xcopy "%csharpDir%CadExOBJNet.dll"     "%destinationDir%" /y
xcopy "%csharpDir%CadExParaNet.dll"    "%destinationDir%" /y
xcopy "%csharpDir%CadExPLYNet.dll"     "%destinationDir%" /y
xcopy "%csharpDir%CadExPRCNet.dll"     "%destinationDir%" /y
xcopy "%csharpDir%CadExRhinoNet.dll"   "%destinationDir%" /y
xcopy "%csharpDir%CadExSLDENet.dll"    "%destinationDir%" /y
xcopy "%csharpDir%CadExSLDNet.dll"     "%destinationDir%" /y
xcopy "%csharpDir%CadExSTEPNet.dll"    "%destinationDir%" /y
xcopy "%csharpDir%CadExSTLNet.dll"     "%destinationDir%" /y
xcopy "%csharpDir%CadExU3DNet.dll"     "%destinationDir%" /y
xcopy "%csharpDir%CadExUnity.dll"      "%destinationDir%" /y
xcopy "%csharpDir%CadExUSDNet.dll"     "%destinationDir%" /y
xcopy "%csharpDir%CadExVRMLNet.dll"    "%destinationDir%" /y
xcopy "%csharpDir%CadExX3DNet.dll"     "%destinationDir%" /y
xcopy "%csharpDir%CadExX3DPDFNet.dll"  "%destinationDir%" /y
xcopy "%csharpDir%CadExX3MFNet.dll"    "%destinationDir%" /y
xcopy "%csharpDir%FreeImageNET.dll"    "%destinationDir%" /y

xcopy "%nativeDir%CadExA3DS.dll"       "%destinationDir%" /y
xcopy "%nativeDir%CadExACIS.dll"       "%destinationDir%" /y
xcopy "%nativeDir%CadExAdvGeom.dll"    "%destinationDir%" /y
xcopy "%nativeDir%CadExBRep.dll"       "%destinationDir%" /y
xcopy "%nativeDir%CadExCAT.dll"        "%destinationDir%" /y
xcopy "%nativeDir%CadExCollada.dll"    "%destinationDir%" /y
xcopy "%nativeDir%CadExCore.dll"       "%destinationDir%" /y
xcopy "%nativeDir%CadExCreo.dll"       "%destinationDir%" /y
xcopy "%nativeDir%CadExDS3DXML.dll"    "%destinationDir%" /y
xcopy "%nativeDir%CadExDWG.dll"        "%destinationDir%" /y
xcopy "%nativeDir%CadExDXF.dll"        "%destinationDir%" /y
xcopy "%nativeDir%CadExFBX.dll"        "%destinationDir%" /y
xcopy "%nativeDir%CadExGLTF.dll"       "%destinationDir%" /y
xcopy "%nativeDir%CadExIFC.dll"        "%destinationDir%" /y
xcopy "%nativeDir%CadExIGES.dll"       "%destinationDir%" /y
xcopy "%nativeDir%CadExINV.dll"        "%destinationDir%" /y
xcopy "%nativeDir%CadExJT.dll"         "%destinationDir%" /y
xcopy "%nativeDir%CadExMesh.dll"       "%destinationDir%" /y
xcopy "%nativeDir%CadExNX.dll"         "%destinationDir%" /y
xcopy "%nativeDir%CadExOBJ.dll"        "%destinationDir%" /y
xcopy "%nativeDir%CadExPara.dll"       "%destinationDir%" /y
xcopy "%nativeDir%CadExPLY.dll"        "%destinationDir%" /y
xcopy "%nativeDir%CadExPRC.dll"        "%destinationDir%" /y
xcopy "%nativeDir%CadExRhino.dll"      "%destinationDir%" /y
xcopy "%nativeDir%CadExSLD.dll"        "%destinationDir%" /y
xcopy "%nativeDir%CadExSLDE.dll"       "%destinationDir%" /y
xcopy "%nativeDir%CadExSTEP.dll"       "%destinationDir%" /y
xcopy "%nativeDir%CadExSTL.dll"        "%destinationDir%" /y
xcopy "%nativeDir%CadExU3D.dll"        "%destinationDir%" /y
xcopy "%nativeDir%CadExUSD.dll"        "%destinationDir%" /y
xcopy "%nativeDir%CadExView.dll"       "%destinationDir%" /y
xcopy "%nativeDir%CadExVRML.dll"       "%destinationDir%" /y
xcopy "%nativeDir%CadExX3D.dll"        "%destinationDir%" /y
xcopy "%nativeDir%CadExX3DPDF.dll"     "%destinationDir%" /y
xcopy "%nativeDir%CadExX3MF.dll"       "%destinationDir%" /y
xcopy "%nativeDir%freeimage.dll"       "%destinationDir%" /y
xcopy "%nativeDir%freetype.dll"        "%destinationDir%" /y
xcopy "%nativeDir%geom.dll"            "%destinationDir%" /y
xcopy "%nativeDir%tbb.dll"             "%destinationDir%" /y
xcopy "%nativeDir%tbbmalloc.dll"       "%destinationDir%" /y
xcopy "%nativeDir%vis.dll"             "%destinationDir%" /y